### ISSUE TITLE
Launching surftrak (tracking issue)

### ISSUE THREAD

**Issue by clydemcqueen** [clydemcqueen/ardusub_surftrak#4]
Remaining tasks:
- [x] Additional in-water tests
- [x] Come up with a plan to use RNG_HOLD mode and AUTO mode at the same time
- [x] Add support for rangefinder signal_quality https://github.com/ArduPilot/ardupilot/pull/25550  
- [x] Main PR https://github.com/ArduPilot/ardupilot/pull/23435
- [ ] Send A50 signal_quality to ArduSub https://github.com/bluerobotics/BlueOS-Water-Linked-DVL/issues/32
- [x] Add support in QGC https://github.com/mavlink/qgroundcontrol/pull/11126
- [x] Add support in cockpit https://github.com/bluerobotics/cockpit/issues/786
- [x] Promote ArduSub 4.5 to stable
- [x] Support "above terrain" frame in auto and guided modes https://github.com/ArduPilot/ardupilot/pull/26450

**Comment by clydemcqueen** [comment]
There is one small improvement outstanding, but SURFTRAK has been launched in 4.5, and it is working well.
